name: Reusable Docker Push Workflow

on:
  workflow_call:

env:
    DOTNET_VERSION: '6.0.x' # set this to the dot net version to use

jobs:
    build:
        runs-on: ubuntu-latest
        environment: Production
        defaults:
            run:
                working-directory: ./src/EventsAPI
        steps:
            - uses: actions/checkout@v2
            - name: Build the Docker image
              run: docker build . --file Dockerfile --tag git_docker:$(date +%s)

            - name: Login to Docker Hub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKER_HUB_USERNAME }}
                  password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
              with:
                  images: seanraff89/SignalServer

            - name: Build and push Docker image
              uses: docker/build-push-action@v3
              with:
                  context: ./src/SignalServer
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}